services:
  backend:
    build: ./back
    container_name: backend
    expose:
      - "8000"
    networks:
      - nginx

  frontend:
    build: ./front
    container_name: frontend
    expose:
      - "8080"
    depends_on:
      - backend
    networks:
      - nginx

  nginx-proxy:
    build: ./prod/nginx-prod
    container_name: nginx-proxy
    ports:
      - "8000:443"
      - "8080:443"
    volumes:
      - tls_certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    networks:
      - nginx

volumes:
  tls_certs:

networks:
  nginx:
    driver: bridge

