services:
  backend:
    build: ./back
    container_name: backend
    expose:
      - "8000"

  frontend:
    build: ./front
    container_name: frontend
    expose:
      - "80"
    depends_on:
      - backend

  nginx-proxy:
    build: ./prod/nginx-prod
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - tls_certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend

volumes:
  tls_certs:
