services:
  backend:
    build: ./back
    container_name: backend
    ports:
      - "8000:8000"

  frontend:
    build: ./front
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
