POST http://localhost:8000/api/login/ HTTP/1.1
content-type: application/json

{
    "username": "user",
    "password": "user1234"
}

###
GET http://localhost:8000/api/profile/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc4MjE1MTYwLCJpYXQiOjE3NzQ2MTUxNjAsImp0aSI6ImE0MWUzZTc4ZTJjYzQ4MTliMmUxNDQ0MjcwZTUyNjk4IiwidXNlcl9pZCI6IjIifQ.zg5s7dXlDgrUSyt91zvxk2jLWV_yAZFIYOiVGcGP4go

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}


###
GET http://localhost:8000/api/friends/search/?name=r HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc4MjE1MTYwLCJpYXQiOjE3NzQ2MTUxNjAsImp0aSI6ImE0MWUzZTc4ZTJjYzQ4MTliMmUxNDQ0MjcwZTUyNjk4IiwidXNlcl9pZCI6IjIifQ.zg5s7dXlDgrUSyt91zvxk2jLWV_yAZFIYOiVGcGP4go

{
    
}
