# Generated by Django 6.0.3 on 2026-04-07 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('duel', 'Duel'), ('tournament', 'Tournament')], default='duel', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('live', 'Live'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='waiting', max_length=20)),
                ('map_name', models.CharField(default='default', max_length=64)),
                ('score_limit', models.PositiveIntegerField(default=5)),
                ('time_limit', models.PositiveIntegerField(default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('none', 'None'), ('win', 'Win'), ('loss', 'Loss')], default='none', max_length=20)),
                ('is_ready', models.BooleanField(default=False)),
                ('is_joined', models.BooleanField(default=False)),
                ('health', models.IntegerField(default=100)),
                ('score', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='match.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='match_match_status_0fe4ae_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['created_at'], name='match_match_created_b51748_idx'),
        ),
        migrations.AddIndex(
            model_name='matchplayer',
            index=models.Index(fields=['match'], name='match_match_match_i_c308b2_idx'),
        ),
        migrations.AddIndex(
            model_name='matchplayer',
            index=models.Index(fields=['user'], name='match_match_user_id_b7c1f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchplayer',
            constraint=models.UniqueConstraint(fields=('match', 'user'), name='uniq_user_per_match'),
        ),
    ]
