# Generated by Django 6.0.3 on 2026-04-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='mode',
        ),
        migrations.AddField(
            model_name='match',
            name='players_maxcount',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
