# Generated by Django 5.2.12 on 2026-04-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_remove_match_mode_match_players_maxcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchplayer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
