# Generated by Django 6.0.3 on 2026-03-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='wait_accept',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='want_to_be_friend',
        ),
    ]
